version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.0
    working_directory: ~/sources
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: |
          yarn install --frozen-lockfile
          yarn clean
          yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  unit_test:
    docker:
      - image: circleci/node:12.16.0
    working_directory: ~/sources
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: |
          yarn test --verbose --coverage
          cat coverage/lcov.info | yarn coveralls
  integration_test:
    docker:
      - image: circleci/node:12.16.0
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
    working_directory: ~/sources
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: .circleci/test-skeleton.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integration_test:
          requires:
            - unit_test
